# Powerlevel10k prompt configuration.
# Generated by `p10k configure` — run it to customize your prompt.
# This stub enables instant prompt and triggers the wizard on first login.

# Instant prompt mode: off | quiet | verbose
typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

# Run configuration wizard if no config has been generated yet.
# Remove this block after running `p10k configure` once.
if [[ ! -f ~/.p10k.zsh ]] || [[ $(wc -l < ~/.p10k.zsh) -lt 50 ]]; then
  echo "Run 'p10k configure' to set up your prompt."
fi
